<div class="valign tag_welcome">
	<div class="tag_wel_middle">
		<div class="container">
			<div class="wow_content tag_auth_box tag_auth_box_auto">
			<img src="<?php echo $wo['config']['theme_url']; ?>/img/forgot.svg" class="image-forgot" alt="" />
				<?php
					$allow_switch = false;
					if ($wo['config']['sms_provider'] == 'twilio') {
						if( $wo['config']['sms_twilio_username'] !== "" AND  $wo['config']['sms_twilio_password'] !== "" ){
							if( $wo['config']['emailValidation'] == 1 ) {
								if( $wo['config']['sms_or_email'] == "sms" ) {
									$allow_switch = true;
								}
							}
						}
					} else if ($wo['config']['sms_provider'] == 'bulksms') {
						if( $wo['config']['sms_username'] !== "" AND  $wo['config']['sms_password'] !== "" ){
							if( $wo['config']['emailValidation'] == 1 ) {
								if( $wo['config']['sms_or_email'] == "sms" ) {
									$allow_switch = true;
								}
							}
						}
					} else if ($wo['config']['sms_provider'] == 'infobip') {
						if( $wo['config']['infobip_api_key'] !== "" AND  $wo['config']['infobip_base_url'] !== "" ){
							if( $wo['config']['emailValidation'] == 1 ) {
								if( $wo['config']['sms_or_email'] == "sms" ) {
									$allow_switch = true;
								}
							}
						}
					}
				?> 
				<?php if( $allow_switch ){ ?>
					<form class="x_chooser">
						<p class="title"><?php echo $wo['lang']['forgot_your_password']; ?></p>
						<div class="wow_forgot_choice">
							<button type="button" class="btn btn-main-rev btn-mat tag_wel_btn" id="recover_password_by_email"><?php echo $wo['lang']['recover_password_by_email']?></button>
							<button type="button" class="btn btn-main-rev btn-mat tag_wel_btn" id="recover_password_by_sms"><?php echo $wo['lang']['recover_password_by_sms']?></button>
						</div>
					</form>
				<?php } ?>
				<form id="forgot-form" class="recover_password_by_email" method="post" <?php if( $allow_switch ){ echo 'style="display: none;"'; } ?>>
					<div class="valign tag_auth_animation d-none"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 367.805 367.805" xml:space="preserve"> <g> <path style="fill:#3BB54A;" d="M183.903,0.001c101.566,0,183.902,82.336,183.902,183.902s-82.336,183.902-183.902,183.902 S0.001,285.469,0.001,183.903l0,0C-0.288,82.625,81.579,0.29,182.856,0.001C183.205,0,183.554,0,183.903,0.001z"/> <polygon style="fill:#fff;" points="285.78,133.225 155.168,263.837 82.025,191.217 111.805,161.96 155.168,204.801 256.001,103.968"/> </g></svg><?php echo $wo['lang']['email_sent'] ?><a class="dec" href="<?php echo $wo['config']['site_url'];?>"><?php echo $wo['lang']['login']?></a></div>
					<p class="title"><?php echo $wo['lang']['forgot_your_password']; ?></p>
					<div class="errors"></div>
					<label class="tag_field">
						<input class="tag_field1" name="recoveremail" type="email" autocomplete="off" placeholder=" " required>
						<span><?php echo $wo['lang']['email']?></span>
					</label>
					<?php if($wo['config']['reCaptcha'] == 1) {?>
						<div class="form-group">
							<div class="g-recaptcha" data-sitekey="<?php echo $wo['config']['reCaptchaKey']?>"></div>
						</div>
					<?php } ?>
					<button type="submit" class="btn btn-main btn-mat disable_btn tag_wel_btn"><?php echo $wo['lang']['recover_password']?></button>
				</form>
				<form id="forgot-form-sms" class="recover_password_by_sms" method="post" style="display: none;">
					<div class="valign tag_auth_animation d-none"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 367.805 367.805" xml:space="preserve"> <g> <path style="fill:#3BB54A;" d="M183.903,0.001c101.566,0,183.902,82.336,183.902,183.902s-82.336,183.902-183.902,183.902 S0.001,285.469,0.001,183.903l0,0C-0.288,82.625,81.579,0.29,182.856,0.001C183.205,0,183.554,0,183.903,0.001z"/> <polygon style="fill:#fff;" points="285.78,133.225 155.168,263.837 82.025,191.217 111.805,161.96 155.168,204.801 256.001,103.968"/> </g></svg><?php echo $wo['lang']['recoversms_sent'] ?></div>
					<p class="title"><?php echo $wo['lang']['forgot_your_password']; ?></p>
					<div class="errors"></div>
					<label class="tag_field">
						<input name="recoverphone" type="tel" autocomplete="off" placeholder=" " required>
						<span><?php echo $wo['lang']['phone_number']?></span>
					</label>
					<button type="submit" class="btn btn-main btn-mat disable_btn tag_wel_btn"><?php echo $wo['lang']['recover_password']?></button>
				</form>
				<div class="text-center tag_wel_register"><?php echo $wo['lang']['already_have_account']?> <a class="dec" href="<?php echo $wo['config']['site_url'];?>"><?php echo $wo['lang']['login']?></a></div>
			</div>
		</div>
	</div>
	<div class="tag_wel_bottom">
		<?php echo Wo_LoadPage('footer/welcome');?>
	</div>
</div>

<script>
var working = false;
var $this = $('#forgot-form');
var $this_sms = $('#forgot-form-sms');
var $state = $this.find('.errors');
var $state_sms = $this_sms.find('.errors');
var $login_anim = $this.find('.tag_auth_animation');
var $login_anim_phone = $this_sms.find('.tag_auth_animation');

$(function() {
	$('#recover_password_by_email').click(function(){
		$('.x_chooser').hide();
		$('.recover_password_by_email').show();
	});
	$('#recover_password_by_sms').click(function(){
		$('.x_chooser').hide();
		$('.recover_password_by_sms').show();
	});

	Wo_SetTimer();
	$this.ajaxForm({
		url: Wo_Ajax_Requests_File() + '?f=recover',
		beforeSend: function() {
			working = true;
			$this.find('.disable_btn').attr("disabled", true);
		},
		success: function(data) {
			if (data.status == 200) {
				$login_anim.removeClass('d-none');
			} else {
				$this.find('.disable_btn').attr("disabled", false);
				$state.html(data.errors);
			}
			working = false;
		}
	});

	$this_sms.ajaxForm({
		url: Wo_Ajax_Requests_File() + '?f=recoversms',
		beforeSend: function() {
			working = true;
			$this_sms.find('.disable_btn').attr("disabled", true);
		},
		success: function(data) {
			if (data.status == 200) {
				$login_anim_phone.removeClass('d-none');
				setTimeout(function () {
					window.location.href = data.location;
				}, 1000);
			} else {
				$this_sms.find('.disable_btn').attr("disabled", false);
				$state_sms.html(data.errors);
			}
			working = false;
		}
	});
});
</script>